### ISSUE TITLE
Change license to MPL?

### ISSUE THREAD

**Issue by QuietMisdreavus** [QuietMisdreavus/twitter-rs#10]
When I initially released egg-mode, I wanted to release it under the LGPL, hoping that the library itself would be copyleft without forcing its consumers to be. However, since the terms of the LGPL specifically mention dynamic linking, this would be difficult-to-impossible to actually carry out in the Rust world, where libraries on crates.io are distributed as source and statically built into the final binary. Once this was pointed out to me, I quickly relicensed 0.1.1 as Apache2 and carried on.

Recently, the Mozilla Public License was pointed out to me. It seems to be a less-stringent copyleft, where the license applies to marked source files themselves, rather than the compilation unit as a whole. In other words, forks are copyleft, consumers aren't, just like I wanted in the beginning.

If this were still early days, I could switch and carry on. However, I'm not the only one with code in this repo any more. Fortunately, there's not that many, so I can feasibly just ask everyone in here.

To be sure, the question being asked of everyone mentioned here is: *Are you okay if I relicense the next version of egg-mode to MPL?* This would relicense your code contributions, so I'd like your approval before I make the switch.

- [x] @serprex
- [x] @frewsxcv
- [x] @d12i
- [x] @jkarns275

**Comment by serprex** [comment]
I approve

**Comment by frewsxcv** [comment]
I release all copyright claims on the code I've committed to this repository. Do what you wish with my work.

**Comment by jkarns275** [comment]
I approve.

**Comment by QuietMisdreavus** [comment]
Thank you all so much! egg-mode kinda got back-burnered for me for the moment, but when I release the next version I'll change the license over.
