### ISSUE TITLE
migrate to serde and remove FromJson

### ISSUE THREAD

**Issue by QuietMisdreavus** [QuietMisdreavus/twitter-rs#11]
With the official deprecation of rustc-serialize, it's worth investigating what it would take to migrate onto serde 1.0. A quick migration would just swap out rustc-serialize's json handling with serde-json, but it might be possible to take out FromJson entirely and just annotate the structs themselves with the special handling I've used there so far.

This will affect the minimum rust version that egg-mode will compile with: Right now I've had an unspoken goal to support a few versions back of Rust, without committing to anything specific. The last time I checked, the earliest version I could use was 1.13, due to `*ring*`. Moving fully over to serde would bump this up to 1.15, due to the use of custom derive. It's not *that* big of a deal, just something to note. (And something to add to the travis/appveyor configurations, when the switch happens, to formally commit to a minimum supported version.)

**Comment by QuietMisdreavus** [comment]
Update to the version compatibility note: The update to `*ring*` 0.9.4 (#13) pins me to rust 1.17 anyway from its use of `untrusted` 0.5.0.

**Comment by dtolnay** [comment]
Let us know in #serde IRC or the issue tracker if you get stuck!

**Comment by adwhit** [comment]
Hey, thought I'd let you know that I'm having a crack at this issue. I'm trying to do it without an API changes.
Obviously it's a major refactor. Progress so far: https://github.com/adwhit/twitter-rs/commits/serde
