### ISSUE TITLE
Change KeyPair to use Cow<'static, str>?

### ISSUE THREAD

**Issue by QuietMisdreavus** [QuietMisdreavus/twitter-rs#14]
Currently, there's some lifetime proliferation surrounding tokens because the elements of KeyPair are storing `Cow<'a, str>`. This is primarily used within the examples to allow for the use of string literals (via `include_str!()` for the consumer key. This can easily be accommodated with a `Cow<'static, str>` without adding lifetimes to KeyPair, and by extension Token. The only problem is that I don't know whether any users of egg-mode use a non-static lifetime here.

**Comment by jkarns275** [comment]
I don't think it is worth doing, you would gain very little and it would prevent anyone who currently uses a non-static lifetime from continuing to do so, and prevent anyone from doing it in the future.

**Comment by QuietMisdreavus** [comment]
Yeah, that's the thing. I call it "lifetime proliferation", but I don't actually have any of that because it can just be elided out in function signatures. The only place it would really be a problem is if a library user had a "state" struct that held onto a Token, since lifetimes can't be elided within struct definitions.

**Comment by jkarns275** [comment]
Having a state struct wouldn't be such a bad idea for a user to implement, it might help avoid horribly long main functions (which I encountered [here](https://github.com/jkarns275/CSC-365/blob/master/src/main.rs#L68). More than that, if the user wants to dynamically choose which token to load at runtime, this change wouldn't allow that.

**Comment by QuietMisdreavus** [comment]
Sure you can, you can always clone an owned String, and it'll convert into a Cow::Owned when you hand it to KeyPair::new. If you gave a regular &str reference, you'd have to make sure your source Strings outlived your State - while not actually containing them within your State, because that would make it a self-referencing struct. I'm not sure how useful that is, if your State (or whatever you hold your Tokens/KeyPairs in) is intended to be alive for the life of the program.

**Comment by jkarns275** [comment]
I seem to have misunderstood the proposition - I'm going to read up on the docs 😄

**Comment by QuietMisdreavus** [comment]
A `Cow<'a, str>` is in one of two states: Owned (a `String`) or Borrowed (a `&'a str`). The `'a` lifetime param is a regular lifetime param, as if you were holding a `&'a str`, so needs to be treated as such. If you have an instance of `Cow::Owned`, it's holding no reference at all, so it's effectively of type `Cow<'static, T>`. (I mention this in the [`KeyPair::new`] docs, but it's buried underneath all the auth documentation, so I don't expect that to be fresh in mind. `>_>`) However, there's another way to get a `'static` lifetime in your Cow: a `Cow::Borrowed` that has a `'static` lifetime to its reference. Therefore, a `Cow<'static, str>` can be two things: a string literal, or an owned String.

[`KeyPair::new`]: https://tonberry.quietmisdreavus.net/doc/egg_mode/struct.KeyPair.html#method.new

The reason the keys are Cows in the first place is to allow string literals for your keys without having to allocate a String for them. With this in mind, moving them to `Cow<'static, str>` is more in line with my intent. However, since they've had a regular lifetime param for this long, I'm not sure if I can make that change without breaking someone's flow. We're still pre-1.0, but it's been around long enough and it's getting close enough to feature-completeness that I'm taking the precaution all the same.

**Comment by jkarns275** [comment]
Knowing that it seems like the change would be fairly non consequential either way. It might save one allocation at the beginning of a program (?), but that isn't really worth the change since it might break things, and things will function the same still (right?). If things did break though, the fix would probably be really simple to implement.

This change seems a bit superfluous, but it is your library and if that is more of the style you want things to be, by all means you should make it ^_^

**Comment by QuietMisdreavus** [comment]
It's a little superfluous, sure, but in my head it saves a lifetime param and doesn't affect my intended or anticipated uses of the KeyPair struct. It does, however, restrict some possible use of the types and that's what made me hesitate.

On the other hand, I've gotten this far by making it an opinionated library, so maybe I could just do it and add the requisite "**breaking change**" note in the changelog, like all the others. Need at least one breaking change per major release, right? :wink:
