### ISSUE TITLE
Unstable use of struct

### ISSUE THREAD

**Issue by luki** [QuietMisdreavus/twitter-rs#15]
``` 
struct field shorthands are unstable (see issue #37340)
   --> /Users/l/.cargo/registry/src/github.com-1ecc6299db9ec823/untrusted-0.5.0/src/untrusted.rs:313:21
    |
313 |             Slice { bytes }
    |                     ^^^^^

error: struct field shorthands are unstable (see issue #37340)
   --> /Users/l/.cargo/registry/src/github.com-1ecc6299db9ec823/untrusted-0.5.0/src/untrusted.rs:327:51
    |
327 |             self.bytes.get(r).map(|bytes| Slice { bytes })
    |                                                   ^^^^^

error: aborting due to 2 previous errors
```

**Comment by QuietMisdreavus** [comment]
That error is coming out of `untrusted`, which is a dependency of `*ring*`. Which rustc version are you using? Struct field init shorthand was stabilized in rustc 1.17.0.

**Comment by luki** [comment]
I am using rustc 1.14.0

**Comment by QuietMisdreavus** [comment]
Sorry, since it's not my crate that caused this, I'm going to close the issue. [`untrusted`](https://github.com/briansmith/untrusted) bumped the minimum required rust version for egg-mode to 1.17.0.

**Comment by luki** [comment]
I've been using your crate before that version though :')

**Comment by QuietMisdreavus** [comment]
I think the update that included that crate was when I bumped `ring` in 0.8.1? Try setting your dependency to `egg-mode = "=0.8.0"` and see if that works.

**Comment by luki** [comment]
Cool, I was trying out to go one down before, but that didn't help so maybe that. I asked before trying out more, the later the version the better (y)

**Comment by QuietMisdreavus** [comment]
Yeah, I made a patch release when #13 was made, because people were having issues with multiple versions of `*ring*` in their project. At the same time, that new version of `*ring*` bumped their version of `untrusted`, which caused this issue you're having right now.
