### ISSUE TITLE
Using f32 for search::Distance enum for more accuracy 

### ISSUE THREAD

**Issue by umurgdk** [QuietMisdreavus/twitter-rs#17]
Official twitter docs says, when the accuracy parameter is just a number without a unit suffix (like km/ft) it should be considered as `meters`. But my tests showed sending meters doesn't works as expected on the twitter side. Surprisingly sending floating point numbers as `km` works much better (for example accuracy=0.4km) I needed that kind of accuracy in one of my projects, just cloned and maked the changes.  I wanted to get your opinion about changung Distance unit's types to `f32` from `u32` before creating a pull request.

**Comment by QuietMisdreavus** [comment]
I apparently didn't even consider using floating-point numbers for that! That sounds like a good change, go ahead and open the PR.

**Comment by QuietMisdreavus** [comment]
Since https://github.com/QuietMisdreavus/twitter-rs/pull/20 got merged, I'll close this.
