### ISSUE TITLE
Release current HEAD?

### ISSUE THREAD

**Issue by nabijaczleweli** [QuietMisdreavus/twitter-rs#2]
There's a lot of new changes from the latest released version (`v0.3.0`) (such as the corest features like posting tweets) and I'd like to use them, can you put up a release on `crates.io`?

**Comment by QuietMisdreavus** [comment]
Properly *posting* tweets isn't implemented yet, actually. That's on the to-do list this week. I'm hoping to get the basic actions (like/unlike, retweet/unretweet, post/delete) and maybe searches written and pushed before cutting another release. Specifically, I'm hoping to check all the boxes in TODO.md between `statuses/mentions_timeline` and `favorites/destroy`. That said, only search and posting are going to be new work; everything else falls into patterns that already exist here. I'd like to get it pushed to crates.io before this weekend.

**Comment by nabijaczleweli** [comment]
Cool, thanks :)
