### ISSUE TITLE
migrate to hyper 0.12

### ISSUE THREAD

**Issue by QuietMisdreavus** [QuietMisdreavus/twitter-rs#45]
I should bump egg-mode to take advantage of the new release of hyper. This issue collects my thoughts on what it would take.

- [ ] Migrate from typed headers to `http`-style headers
  - [ ] `auth::TwitterOAuth` can change its `Scheme` impl to a `Display` impl, effectively formatting `"OAuth {}"` with the contents of `fmt_scheme`
  - [ ] `ContentType` is used to set either url-encoded or json, so i can cut out the `mime` crate and use the strings directly
  - [ ] `make_future`'s closure takes the headers, so that would need to take a `HeaderMap` instead
  - [ ] the rate-limit parsing uses custom headers, which is the most common consumer of those headers
- [ ] Functions no longer need to take a `Handle`, as the tokio runtime can implicitly use one
  - [ ] ...how does the tokio runtime work anyway `>_>` Need to decide how to adjust documentation, whether to build hyper with its tokio runtime re-export, etc

...not sure about what else? Will probably learn more as i start the switch.

**Comment by ejmg** [comment]
hi there, I'm really trying to get into rust more before I head out to RustConf this August. I would be willing to definitely help with this if I could get some guidance?
