### ISSUE TITLE
Does not build with openssl 1.1.1

### ISSUE THREAD

**Issue by jonhoo** [QuietMisdreavus/twitter-rs#48]
`egg-mode` currently depends on `hyper-tls 0.1`, which pulls in `openssl 0.9.24`, which doesn't build with the most recent version of openssl (sfackler/rust-openssl#994). I tried to see if I could get away with just bumping `hyper-tls` and `native-tls`, but sadly that doesn't work either. `hyper-tls 0.2` still uses the old `openssl`, and `hyper-tls 0.3` requires `hyper 0.12`, and thus #45. It could be that there's some magical workaround, but for the time being, we're locked in a situation where the crate doesn't build until we bump `hyper` :'(

**Comment by thebitstick** [comment]
Planned on integrating egg-mode into https://github.com/ShareXin/ShareXin in place of my current solution (a bad one) for communicating with with Twitter API.
But this openssl issue made me take it off my dependencies!

**Comment by ao2** [comment]
Thanks for the fixes, I hit this problem when compiling https://github.com/klausi/mastodon-twitter-sync
