### ISSUE TITLE
Create a 0.13 release

### ISSUE THREAD

**Issue by klausi** [QuietMisdreavus/twitter-rs#50]
Hi there and thanks a lot for this super useful library!

There is currently stuff on the master branch to make egg-mode work with OpenSSL 1.1.1 (I think the Hyper update enables that). Could you make some kind of release so that I don't have to hack in the master branch as dependency for https://github.com/klausi/mastodon-twitter-sync/issues/5 ? Maybe 0.13-beta1 or something?

Thanks!

**Comment by adwhit** [comment]
This is getting close, I hope to get it out in the coming week.

I would like to get back onto a fairly short release cycle, so `0.14` won't be too long after.

**Comment by QuietMisdreavus** [comment]
@adwhit I've gone ahead and added you as an owner of the crate on crates.io, so feel free to cut a release once you feel ready.

**Comment by adwhit** [comment]
@QuietMisdreavus Tried to release `0.13` just now, seems I'm still not an owner?

**Comment by QuietMisdreavus** [comment]
I think crates.io sends an invitation when you add a crate owner. Can you check https://crates.io/me/pending-invites and see if it's still there?

**Comment by adwhit** [comment]
Doh, sorry! `0.13` is out!
