### ISSUE TITLE
Missing .try_for_each() method in stream::TwitterStream

### ISSUE THREAD

**Issue by Kydlaw** [QuietMisdreavus/twitter-rs#85]
Hey everyone!

While trying to use the streaming interface, I received this error using the example in the documentation:

```error[E0599]: no method named `try_for_each` found for struct `egg_mode::stream::TwitterStream` in the current scope```

My code:
```
    let stream = filter()
        // find tweets mentioning any of the following:
        .track(&["rustlang", "python", "java", "javascript"])
        .start(&token);

    stream
        .try_for_each(|m| {
            // Check the message type and print tweet to console
            if let StreamMessage::Tweet(tweet) = m {
                println!(
                    "Received tweet from {}:\n{}\n",
                    tweet.user.unwrap().name,
                    tweet.text
                );
            }
            futures::future::ok(())
        })
        .await
        .expect("Stream error");
```

Did this method disappeared? Thanks for your help!

**Comment by adwhit** [comment]
Hi there.

The method certainly exists: https://docs.rs/futures/0.3.4/futures/stream/trait.TryStreamExt.html#method.try_for_each

Some ideas:
* Are you using the latest version of `futures` (`0.3.4`)?
* are you importing the trait? e.g. `use futures::TryStreamExt`

**Comment by Kydlaw** [comment]
Huh... wrong version of futures indeed...
Sorry for the stupid issue :/
I'm still getting use to the dependency management in Rust.

Closing this and thank you for your quick answer.
