### ISSUE TITLE
Can `FutureResponse<T>` implement `Send`?

### ISSUE THREAD

**Issue by kuretchi** [QuietMisdreavus/twitter-rs#86]
Currently, [`tweet::TimelineFuture`](https://docs.rs/egg-mode/0.14.0/egg_mode/tweet/struct.TimelineFuture.html) and [`user::UserSearch`](https://docs.rs/egg-mode/0.14.0/egg_mode/user/struct.UserSearch.html) do not implement `Send`, and this is due to `FutureResponse<T>`, which is defined as below.

https://github.com/QuietMisdreavus/twitter-rs/blob/24b3aba1d2e95d90b5e4268f2a7a338324f18855/src/common/mod.rs#L204

Is it possible to change this into `Pin<Box<dyn Future<Output = error::Result<Response<T>>> + Send>>`?

**Comment by adwhit** [comment]
I think that would be fine. It is a bit annoying that auto traits do not leak from dyn traits, though I'm sure there's a good reason.

**Comment by kuretchi** [comment]
OK, I'll create a pull request.
